version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: payment_db
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - rabbitmq-network

volumes:
  rabbitmq_data:
  # postgres_data:

networks:
  rabbitmq-network:
    driver: bridge

